name: fee_app
description: "Aplicación móvil Osisnt."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  characters: ^1.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: 10.3.2
  flutter_svg: ^2.3.0
  http: ^1.6.0
  passkeys: 2.22.3
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/raster/
    - assets/logo/vector/
    - assets/logo/standalone/
    - assets/logo/frames_120/
    - assets/logo/frames_120_white/
